version: '3'
services:
  scep:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_ROLE_ID: '${SCEP_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
    ports:
      - ${SCEP_HTTP_LISTEN_PORT}:${SCEP_HTTP_LISTEN_PORT}
    networks:
      - enroller-net
    ports:
      - ${SCEP_HTTP_LISTEN_PORT}:${SCEP_HTTP_LISTEN_PORT}
  scepdb:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: '${SCEP_POSTGRESDB}'
      POSTGRES_USER: '${SCEP_POSTGRESUSER}'
      POSTGRES_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      ENROLLER_SCEP_PASSWORD: '${ENROLLER_SCEP_PASSWORD}'
    volumes:
      - 'scep_pg_data:/var/lib/postgresql/data'
      - './create.sql:/docker-entrypoint-initdb.d/create.sql'
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    networks:
      - enroller-net  

volumes:
  scep_pg_data: null
 
networks:
  enroller-net:
    external: true
