version: '3'
services:
  scepproxy:
    build: 
      context: proxy
    volumes:
      - ./proxy/server/certs:${NGINX_SERVER_CERTS}
      - ./proxy/client/certs:${NGINX_CLIENT_CERTS}
    networks:
      - enroller-net
    ports:
      - ${SCEPPROXY_PORT}:443
  scepca4:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA4}'
      SCEP_ROLE_ID: '${SCEP_CA4_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA4_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_HOST: '${SCEP_CA4_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA4_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}
  scepca3:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA3}'
      SCEP_ROLE_ID: '${SCEP_CA3_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA3_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_HOST: '${SCEP_CA3_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA3_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}
  scepca2:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA2}'
      SCEP_ROLE_ID: '${SCEP_CA2_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA2_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_HOST: '${SCEP_CA2_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA2_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}
  scepca1:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA1}'
      SCEP_ROLE_ID: '${SCEP_CA1_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA1_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_HOST: '${SCEP_CA1_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA1_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}
  scepdb:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: '${SCEP_POSTGRESDB}'
      POSTGRES_USER: '${SCEP_POSTGRESUSER}'
      POSTGRES_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      ENROLLER_SCEP_PASSWORD: '${ENROLLER_SCEP_PASSWORD}'
    volumes:
      - 'scep_pg_data:/var/lib/postgresql/data'
      - './create.sql:/docker-entrypoint-initdb.d/create.sql'
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    networks:
      - enroller-net  

volumes:
  scep_pg_data: null
 
networks:
  enroller-net:
    external: true
