version: '3'
services:
  scepextension:
    build:
      context: .
      dockerfile: Dockerfile.extension
    environment:
      SCEPEXTENSION_PORT: '${SCEPEXTENSION_PORT}'
      SCEPEXTENSION_CONSULPROTOCOL: '${SCEPEXTENSION_CONSULPROTOCOL}'
      SCEPEXTENSION_CONSULHOST: '${SCEPEXTENSION_CONSULHOST}'
      SCEPEXTENSION_CONSULPORT: '${SCEPEXTENSION_CONSULPORT}'
      SCEPEXTENSION_CONSULCA: '${SCEPEXTENSION_CONSULCA}'
      SCEPEXTENSION_CERTFILE: '${SCEPEXTENSION_CERTFILE}'
      SCEPEXTENSION_KEYFILE: '${SCEPEXTENSION_KEYFILE}'
      SCEPEXTENSION_SERVERPORT: '${SCEPEXTENSION_SERVERPORT}'
      SCEPEXTENSION_SCEPMAPPING: '${SCEPEXTENSION_SCEPMAPPING}'
      SCEPEXTENSION_PROXYHOST: '${SCEPEXTENSION_PROXYHOST}'
      SCEPEXTENSION_PROXYPORT: '${SCEPEXTENSION_PROXYPORT}'
      JAEGER_SERVICE_NAME: '${SCEPEXTENSION_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${SCEPEXTENSION_JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${SCEPEXTENSION_JAEGER_AGENT_PORT}'
    volumes:
      - ./certs:/certs
    ports:
      - ${SCEPEXTENSION_PORT}:${SCEPEXTENSION_PORT}
    networks:
      - enroller-net

  scepproxy:
    build: 
      context: proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/log:/var/log/nginx
      - ./proxy/server/certs:${NGINX_SERVER_CERTS}
      - ./proxy/client/certs:${NGINX_CLIENT_CERTS}
    ports:
      - 443:443
    networks:
      - enroller-net

  scepca4:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA4}'
      SCEP_VAULT_CA_CERT: '${SCEP_VAULT_CA_CERT}'
      SCEP_ROLE_ID: '${SCEP_CA4_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA4_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_CONSULCA: '${SCEP_CONSULCA}'
      SCEP_HOST: '${SCEP_CA4_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
      JAEGER_SERVICE_NAME: '${SCEP_CA4_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${SCEP_JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${SCEP_JAEGER_AGENT_PORT}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
      - ./certs:/certs
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA4_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}
      
  scepca3:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA3}'
      SCEP_VAULT_CA_CERT: '${SCEP_VAULT_CA_CERT}'
      SCEP_ROLE_ID: '${SCEP_CA3_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA3_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_CONSULCA: '${SCEP_CONSULCA}'
      SCEP_HOST: '${SCEP_CA3_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
      JAEGER_SERVICE_NAME: '${SCEP_CA3_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${SCEP_JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${SCEP_JAEGER_AGENT_PORT}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
      - ./certs:/certs
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA3_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}

  scepca2:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA2}'
      SCEP_VAULT_CA_CERT: '${SCEP_VAULT_CA_CERT}'
      SCEP_ROLE_ID: '${SCEP_CA2_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA2_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_CONSULCA: '${SCEP_CONSULCA}'
      SCEP_HOST: '${SCEP_CA2_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
      JAEGER_SERVICE_NAME: '${SCEP_CA2_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${SCEP_JAEGER_AGENT_HOST}'
      JEGER_AGENT_PORT: '${SCEP_JAEGER_AGENT_PORT}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
      - ./certs:/certs
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA2_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}

  scepca1:
    build: '.'
    environment:
      SCEP_HTTP_LISTEN_PORT: '${SCEP_HTTP_LISTEN_PORT}'
      SCEP_VAULT_ADDRESS: '${SCEP_VAULT_ADDRESS}'
      SCEP_VAULT_CA: '${SCEP_VAULT_CA1}'
      SCEP_VAULT_CA_CERT: '${SCEP_VAULT_CA_CERT}'
      SCEP_ROLE_ID: '${SCEP_CA1_ROLE_ID}'
      SCEP_SECRET_ID: '${SCEP_CA1_SECRET_ID}'
      SCEP_FILE_DEPOT: '${SCEP_FILE_DEPOT}'
      SCEP_DB_NAME: '${SCEP_POSTGRESDB}'
      SCEP_DB_USER: '${SCEP_POSTGRESUSER}'
      SCEP_DB_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      SCEP_DB_HOST: '${SCEP_DB_HOST}'
      SCEP_DB_PORT: '${POSTGRES_PORT}'
      SCEP_CONSULPROTOCOL: '${SCEP_CONSULPROTOCOL}'
      SCEP_CONSULHOST: '${SCEP_CONSULHOST}'
      SCEP_CONSULPORT: '${SCEP_CONSULPORT}'
      SCEP_CONSULCA: '${SCEP_CONSULCA}'
      SCEP_HOST: '${SCEP_CA1_HOST}'
      SCEP_LOG_JSON: '${SCEP_LOG_JSON}'
      JAEGER_SERVICE_NAME: '${SCEP_CA1_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${SCEP_JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${SCEP_JAEGER_AGENT_PORT}'
    volumes:
      - ./ca:${SCEP_FILE_DEPOT}
      - ./certs:/certs
    networks:
      - enroller-net
    ports:
      - ${SCEP_CA1_EXPOSE_PORT}:${SCEP_HTTP_LISTEN_PORT}
    expose:
      - ${SCEP_HTTP_LISTEN_PORT}

  scepdb:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: '${SCEP_POSTGRESDB}'
      POSTGRES_USER: '${SCEP_POSTGRESUSER}'
      POSTGRES_PASSWORD: '${SCEP_POSTGRESPASSWORD}'
      ENROLLER_SCEP_PASSWORD: '${ENROLLER_SCEP_PASSWORD}'
    volumes:
      - 'scep_pg_data:/var/lib/postgresql/data'
      - './create.sql:/docker-entrypoint-initdb.d/create.sql'
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    networks:
      - enroller-net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: "{{.Name}}"  

volumes:
  scep_pg_data: null
 
networks:
  enroller-net:
    external: true
